# Generated by Django 5.0.1 on 2024-01-15 19:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('email', models.EmailField(max_length=300, validators=[django.core.validators.EmailValidator(), django.core.validators.MaxLengthValidator(300)])),
                ('country', models.CharField(max_length=300, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('town', models.CharField(max_length=300, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MaxLengthValidator(20)])),
                ('contact_time', models.CharField(choices=[('anytime', 'Anytime'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=50, validators=[django.core.validators.MaxLengthValidator(50)])),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('subjects', models.CharField(choices=[('anytime', 'Anytime'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=15, validators=[django.core.validators.MaxLengthValidator(15)])),
                ('requirements', models.CharField(choices=[('full time-instead of school', 'Full Time-Instead of School'), ('full time-after schools and weekends', 'Full Time-After Schools and Weekends'), ('full time-during school vacations', 'Full Time-During School Vacations'), ('part time-15+ per week', 'Part Time-15+ Per Week'), ('part time-less than 15 hours per week', 'Part Time-Less Than 15 Hours Per Week')], max_length=400, validators=[django.core.validators.MaxLengthValidator(400)])),
                ('duration', models.CharField(choices=[('anytime', 'Anytime'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=200, validators=[django.core.validators.MaxLengthValidator(200)])),
            ],
        ),
    ]
