# Generated by Django 5.0.1 on 2024-01-20 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
