# Generated by Django 5.0.1 on 2024-01-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('IGCSE', 'IGCSE'), ('GCSE', 'GCSE'), ('AS', 'AS'), ('IB', 'IB'), ('A-LEVELS', 'A-LEVELS'), ('O-LEVELS', 'O-LEVELS'), ('pre-University', 'pre-University'), ('Enhance-Exams', 'Enhance-Exams')], default=0, max_length=300),
        ),
    ]
