# Generated by Django 5.0.1 on 2024-01-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
    ]
