# Generated by Django 5.0.1 on 2024-02-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
