# Generated by Django 5.0.1 on 2024-02-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_instructor_delete_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_related',
            field=models.BooleanField(default=False),
        ),
    ]
