# Generated by Django 5.0.1 on 2024-02-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_course_is_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_related',
            field=models.BooleanField(default=False),
        ),
    ]
