# Generated by Django 5.0.1 on 2024-02-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('physics', 'Physics'), ('art', 'Art'), ('Chemistry', 'Chemistry'), ('History', 'History')], max_length=255),
        ),
    ]
