# Generated by Django 4.2.7 on 2024-02-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
    ]
