# Generated by Django 4.2.7 on 2024-02-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
