# Generated by Django 4.2.7 on 2024-02-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_remove_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='course',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
    ]
