# Generated by Django 5.0.1 on 2024-02-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_degree_teacher_alter_teacher_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_birth',
        ),
    ]
