# Generated by Django 5.0.1 on 2024-02-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_alter_degree_name_alter_teacher_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelor of Education (B.Ed.)', 'Bachelor of Education (B.Ed.)'), ('Postgraduate Certificate in Education (PGCE)', 'Postgraduate Certificate in Education (PGCE)'), ('Bachelor of Arts (BA)', 'Bachelor of Arts (BA)'), ('Master of Education (M.Ed.)', 'Master of Education (M.Ed.):'), ('Continuing Professional Development (CPD)', 'Continuing Professional Development (CPD)')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
    ]
