# Generated by Django 5.0.1 on 2024-02-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_alter_teacher_degree_delete_degree'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedCourse',
        ),
    ]
