# Generated by Django 5.0.1 on 2024-02-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_delete_relatedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_related',
            field=models.BooleanField(default=False),
        ),
    ]
