# Generated by Django 5.0.1 on 2024-02-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_course_is_related'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
