# Generated by Django 5.0.1 on 2024-02-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.TextField(blank=True),
        ),
    ]
